app = "dongsuldongsul"
primary_region = "icn"  # Seoul region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "dongsuldongsul_data"
  destination = "/app/data"

[metrics]
  port = 9091
  path = "/metrics" 